export const BETTER_AUTH_INSTANCE = 'BETTER_AUTH_INSTANCE';
export const KYSELY_INSTANCE = 'KYSELY_INSTANCE';
export const PAYSTACK_CONFIG = 'PAYSTACK_CONFIG';
export const PAYSTACK_CLIENT = 'PAYSTACK_CLIENT';
